id: AF0076709
title: A Combined Guru Yoga for Marpa, Mila, and Gampopa
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:21:33.070917
  last_modified_at: 2022-02-28 23:21:33.070925
