id: AF0076709
title: 'A Drop of Jewels: A Guru Yoga for Lord Gampopa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:21:33.074219
  last_modified_at: 2022-02-28 23:21:33.074224
