id: AF0076709
title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the Three
  Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-02-28 23:21:33.082693
  last_modified_at: 2022-02-28 23:21:33.082700
